import { medicationService } from '../services/medication.service';
import { reminderApi } from './reminder.api';
import { notificationApi } from './notification.api';
import type { TimeRange, ComprehensiveReport } from '../types/report.types';

// MOCK DATA – DEV ONLY – DO NOT SHIP

/**
 * Generate adherence trend data based on time range
 */
const generateAdherenceTrend = (range: TimeRange, baseRate: number): { date: string; rate: number }[] => {
    const days = range === 'today' ? 1 : range === '7d' ? 7 : 30;
    const trend: { date: string; rate: number }[] = [];
    const today = new Date();
    
    for (let i = days - 1; i >= 0; i--) {
        const date = new Date(today);
        date.setDate(date.getDate() - i);
        const variance = Math.random() * 20 - 10; // ±10% variance
        const rate = Math.max(0, Math.min(100, baseRate + variance));
        trend.push({
            date: date.toISOString().split('T')[0],
            rate: Math.round(rate)
        });
    }
    
    return trend;
};

/**
 * REPORT MOCK GENERATOR
 * 
 * Responsibility: Generate analytics from cross-domain mock data.
 * Purely read-only aggregation.
 */
export const reportMockService = {
    generateMockReport: async (range: TimeRange, userId?: string): Promise<ComprehensiveReport> => {
        // Use Promise.allSettled so that if any service fails (e.g. new user with no data),
        // we still return a valid report with zeros instead of throwing.
        const [medsResult, remsResult, notifsResult] = await Promise.allSettled([
            medicationService.getMedications(userId),
            reminderApi.getReminders(userId),
            notificationApi.getNotifications(userId || "00000000-0000-0000-0000-000000000001", 1, 100)
        ]);

        const meds = medsResult.status === 'fulfilled' ? medsResult.value : [];
        const remsData = remsResult.status === 'fulfilled' ? remsResult.value.data : [];
        const notifsData = notifsResult.status === 'fulfilled' ? notifsResult.value.data : [];

        const totalReminders = remsData.length;
        const missedReminders = remsData.filter(r => r.status === 2).length;
        const acknowledgedReminders = remsData.filter(r => r.status === 1).length;
        const adherenceRate = totalReminders > 0
            ? Math.round(((totalReminders - missedReminders) / totalReminders) * 100)
            : 100;

        return {
            reminderPerformance: {
                totalCreated: totalReminders,
                triggeredOnTime: adherenceRate,
                missedTriggers: missedReminders,
                lateTriggers: 0,
                autoGenerated: remsData.filter(r => r.type === 0).length,
                manuallyCreated: remsData.filter(r => r.type === 1).length,
                dailyHistory: [],
                outcomeBreakdown: [
                    { name: 'On-Time', value: totalReminders - missedReminders },
                    { name: 'Missed', value: missedReminders }
                ]
            },
            notificationDelivery: {
                totalSent: notifsData.length,
                deliveredCount: notifsData.filter(n => n.status >= 1).length,
                failedCount: notifsData.filter(n => n.status === 4).length,
                readRate: notifsData.length > 0 ? Math.round((notifsData.filter(n => n.status >= 2).length / notifsData.length) * 100) : 0,
                acknowledgementRate: notifsData.length > 0 ? Math.round((notifsData.filter(n => n.status === 3).length / notifsData.length) * 100) : 0,
                averageRetries: notifsData.length > 0 ? 0.5 : 0,
                maxRetries: 3,
                channelBreakdown: [
                    { name: 'Push', value: Math.floor(notifsData.length * 0.6) },
                    { name: 'In-App', value: Math.floor(notifsData.length * 0.3) },
                    { name: 'SMS', value: Math.floor(notifsData.length * 0.08) },
                    { name: 'Email', value: Math.floor(notifsData.length * 0.02) }
                ],
                recipientBreakdown: [
                    { name: 'Người cao tuổi', value: Math.floor(notifsData.length * 0.7) },
                    { name: 'Người chăm sóc', value: Math.floor(notifsData.length * 0.3) }
                ]
            },
            medicationAdherence: {
                activeMedications: meds.filter(m => m.status === 'Active').length,
                missedRemindersCount: missedReminders,
                acknowledgedCount: acknowledgedReminders,
                pauseResumeHistoryCount: meds.filter(m => m.status === 'Paused').length,
                adherenceTrend: generateAdherenceTrend(range, adherenceRate)
            },
            appointmentCompliance: {
                totalAppointments: remsData.filter(r => r.type === 2).length,
                withReminders: remsData.filter(r => r.type === 2 && r.status !== 2).length,
                withoutReminders: remsData.filter(r => r.type === 2 && r.status === 2).length,
                deliveredBefore: remsData.filter(r => r.type === 2 && r.status === 1).length,
                noShowRiskCount: remsData.filter(r => r.type === 2 && r.status === 2).length
            },
            systemHealth: {
                failuresByReason: notifsData.filter(n => n.status === 4).length > 0 
                    ? [
                        { reason: 'Network timeout', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.5) },
                        { reason: 'Invalid token', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.3) },
                        { reason: 'Service unavailable', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.2) }
                    ]
                    : [],
                retrySuccessRate: notifsData.length > 0 ? 95 : 100,
                averageDelayMs: notifsData.length > 0 ? 250 : 0,
                peakFailureWindows: notifsData.filter(n => n.status === 4).length > 0
                    ? [
                        { window: '00:00-06:00', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.1) },
                        { window: '06:00-12:00', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.3) },
                        { window: '12:00-18:00', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.4) },
                        { window: '18:00-00:00', count: Math.floor(notifsData.filter(n => n.status === 4).length * 0.2) }
                    ]
                    : []
            },
            metadata: {
                range: range,
                timestamp: new Date().toISOString(),
                version: "1.2.0-mock"
            }
        };
    }
};
