name: dm-dakt  # <-- Đổi tên nhóm hiển thị trên Docker Desktop tách biệt hoàn toàn
#version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: elderly-care-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - elderly-care-network

  redis:
    image: redis:latest
    container_name: elderly-care-redis
    ports:
      - "6379:6379"
    networks:
      - elderly-care-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: elderly-care-sqlserver
    ports:
      - "14330:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Student_12345
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - elderly-care-network

  # ========================================================
  # CONTAINER MỚI ĐƯỢC THÊM VÀO ĐÂY (Ví dụ: Công cụ xem DB)
  # ========================================================
  db-adminer:
    image: adminer:latest
    container_name: elderly-care-adminer
    ports:
      - "8080:8080"  # Bạn có thể vào http://localhost:8080 để quản lý SQL Server công khai
    networks:
      - elderly-care-network

networks:
  elderly-care-network:
    driver: bridge

volumes:
  sqlserver-data: