
export type TimeRange = 'today' | '7d' | '30d' | 'custom';

export interface DateRange {
    start: Date;
    end: Date;
}

// 1. Reminder Performance
export interface ReminderPerformance {
    totalCreated: number;
    triggeredOnTime: number; // percentage
    missedTriggers: number;
    lateTriggers: number;
    autoGenerated: number;
    manuallyCreated: number;
    dailyHistory: { date: string; count: number }[];
    outcomeBreakdown: { name: string; value: number }[]; // For Pie Chart: On-Time, Late, Skipped
}

// 2. Notification Delivery
export interface NotificationDelivery {
    totalSent: number;
    deliveredCount: number;
    failedCount: number;
    readRate: number; // percentage
    acknowledgementRate: number; // percentage
    averageRetries: number;
    maxRetries: number;
    channelBreakdown: { name: string; value: number }[]; // Push, SMS, Email, In-app
    recipientBreakdown: { name: string; value: number }[]; // Elderly, Caregiver
}

// 3. Medication Adherence
export interface MedicationAdherence {
    activeMedications: number;
    missedRemindersCount: number;
    acknowledgedCount: number;
    pauseResumeHistoryCount: number;
    adherenceTrend: { date: string; rate: number }[]; // Daily adherence %
}

// 4. Appointment Compliance
export interface AppointmentCompliance {
    totalAppointments: number;
    withReminders: number;
    withoutReminders: number;
    deliveredBefore: number;
    noShowRiskCount: number; // Based on missed reminders
}

// 5. System Health
export interface SystemHealth {
    failuresByReason: { reason: string; count: number }[];
    retrySuccessRate: number;
    averageDelayMs: number;
    peakFailureWindows: { window: string; count: number }[];
}

export interface ComprehensiveReport {
    reminderPerformance: ReminderPerformance;
    notificationDelivery: NotificationDelivery;
    medicationAdherence: MedicationAdherence;
    appointmentCompliance: AppointmentCompliance;
    systemHealth: SystemHealth;
    metadata: {
        range: string;
        timestamp: string;
        version: string;
    };
}
