import {
    PieChart,
    Pie,
    Cell,
    Tooltip,
    Legend,
    ResponsiveContainer,
} from 'recharts';
import { AlertCircle } from 'lucide-react';
import type { ComprehensiveReport } from '../../types/report.types';
import { chartHelpers } from '../../utils/report.charts';
import './ReportSections.css';

interface ReminderPerformanceSectionProps {
    data: ComprehensiveReport;
}

const ReminderPerformanceSection = ({ data }: ReminderPerformanceSectionProps) => {
    const { colors } = chartHelpers;

    return (
        <div className="report-section slide-in">
            <div className="section-header">
                <h2>Độ Chính Xác Nhắc Nhở</h2>
                <p>Kiểm tra độ tin cậy của hệ thống nhắc nhở tự động</p>
            </div>
            <div className="section-grid">
                <div className="chart-container">
                    <h3>Phân Loại Kết Quả</h3>
                    <ResponsiveContainer width="100%" height={300}>
                        <PieChart>
                            <Pie
                                data={data.reminderPerformance.outcomeBreakdown.filter(item => item.value > 0)}
                                innerRadius={60}
                                outerRadius={100}
                                paddingAngle={data.reminderPerformance.outcomeBreakdown.filter(item => item.value > 0).length > 1 ? 5 : 0}
                                dataKey="value"
                                label={(entry) => `${entry.name}: ${entry.value}`}
                            >
                                {data.reminderPerformance.outcomeBreakdown.filter(item => item.value > 0).map((_, index) => (
                                    <Cell key={`cell-${index}`} fill={colors.chart[index % colors.chart.length]} />
                                ))}
                            </Pie>
                            <Tooltip />
                            <Legend />
                        </PieChart>
                    </ResponsiveContainer>
                </div>
                <div className="stats-panel">
                    <div className="stat-row">
                        <span>Tổng số nhắc nhở:</span>
                        <strong>{data.reminderPerformance.totalCreated}</strong>
                    </div>
                    <div className="stat-row">
                        <span>Nhắc nhở bị bỏ lỡ:</span>
                        <strong className="text-danger">{data.reminderPerformance.missedTriggers}</strong>
                    </div>
                    <div className="stat-row">
                        <span>Tự động tạo (Thuốc):</span>
                        <strong>{data.reminderPerformance.autoGenerated}</strong>
                    </div>
                    <div className="stat-row">
                        <span>Tạo thủ công:</span>
                        <strong>{data.reminderPerformance.manuallyCreated}</strong>
                    </div>
                    <div className="stat-info-box">
                        <AlertCircle size={16} />
                        <p>Nhắc nhở được tự động tạo khi thêm lịch uống thuốc hoặc lịch khám.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReminderPerformanceSection;
