import {
    PieChart,
    Pie,
    Cell,
    Tooltip,
    Legend,
    ResponsiveContainer,
} from 'recharts';
import { AlertCircle } from 'lucide-react';
import type { ComprehensiveReport } from '../../types/report.types';
import { chartHelpers } from '../../utils/report.charts';

interface ReminderPerformanceSectionProps {
    data: ComprehensiveReport;
}

const ReminderPerformanceSection = ({ data }: ReminderPerformanceSectionProps) => {
    const { colors } = chartHelpers;

    return (
        <div className="report-section slide-in">
            <div className="section-header">
                <h2>Reminder Trigger Accuracy</h2>
                <p>Auditing the reliability of the Reminder Service triggers.</p>
            </div>
            <div className="section-grid">
                <div className="chart-container">
                    <h3>Outcome Breakdown</h3>
                    <ResponsiveContainer width="100%" height={300}>
                        <PieChart>
                            <Pie
                                data={data.reminderPerformance.outcomeBreakdown}
                                innerRadius={60}
                                outerRadius={100}
                                paddingAngle={5}
                                dataKey="value"
                            >
                                {data.reminderPerformance.outcomeBreakdown.map((_, index) => (
                                    <Cell key={`cell-${index}`} fill={colors.chart[index % colors.chart.length]} />
                                ))}
                            </Pie>
                            <Tooltip />
                            <Legend />
                        </PieChart>
                    </ResponsiveContainer>
                </div>
                <div className="stats-panel">
                    <div className="stat-row">
                        <span>Total Generated:</span>
                        <strong>{data.reminderPerformance.totalCreated}</strong>
                    </div>
                    <div className="stat-row">
                        <span>Missed Triggers:</span>
                        <strong className="text-danger">{data.reminderPerformance.missedTriggers}</strong>
                    </div>
                    <div className="stat-row">
                        <span>Auto-Generated (Meds):</span>
                        <strong>{data.reminderPerformance.autoGenerated}</strong>
                    </div>
                    <div className="stat-info-box">
                        <AlertCircle size={16} />
                        <p>Reminders are automatically generated 1 hour before scheduled medication doses.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReminderPerformanceSection;
