name: elderly_care_app
description: Elderly Care Reminder System — Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  socket_io_client: ^2.0.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To use Google Fonts — add Nunito as asset or via google_fonts package
  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: fonts/Nunito-Regular.ttf
  #       - asset: fonts/Nunito-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Nunito-ExtraBold.ttf
  #         weight: 800
