import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ComprehensiveReport } from "../types/report.types";

/**
 * EXPORT UTILITY
 * 
 * Handles generation and download of report files.
 */
export const exportHelpers = {
    /**
     * Export as JSON for technical audit
     */
    exportAsJSON: (data: ComprehensiveReport) => {
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        exportHelpers.downloadBlob(blob, `audit_report_${Date.now()}.json`);
    },

    /**
     * Export as CSV (Flattened summary)
     */
    exportAsCSV: (data: ComprehensiveReport) => {
        const rows = [
            ['Category', 'Metric', 'Value'],
            ['Reminder', 'Triggered On Time %', data.reminderPerformance.triggeredOnTime],
            ['Reminder', 'Missed Triggers', data.reminderPerformance.missedTriggers],
            ['Notification', 'Delivered Count', data.notificationDelivery.deliveredCount],
            ['Notification', 'Read Rate %', data.notificationDelivery.readRate],
            ['Medication', 'Missed Reminders', data.medicationAdherence.missedRemindersCount],
            ['System', 'Success Rate %', data.systemHealth.retrySuccessRate],
            ['Metadata', 'Range', data.metadata.range],
            ['Metadata', 'Timestamp', data.metadata.timestamp]
        ];

        const csvContent = rows.map(e => e.join(",")).join("\n");
        const blob = new Blob([csvContent], { type: 'text/csv' });
        exportHelpers.downloadBlob(blob, `safety_summary_${Date.now()}.csv`);
    },

    /**
     * Export as PDF (Professional implementation using jspdf)
     */
    exportAsPDF: (data: ComprehensiveReport) => {
        const doc = new jsPDF();
        const timestamp = new Date().toLocaleString();

        // 1. Header
        doc.setFontSize(22);
        doc.setTextColor(52, 152, 219); // CareLink blue
        doc.text("CareLink System Accountability Report", 14, 20);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated on: ${timestamp}`, 14, 30);
        doc.text(`Reporting Period: ${data.metadata.range}`, 14, 35);
        doc.text(`System Version: ${data.metadata.version}`, 14, 40);

        // 2. High Level Summary Table
        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text("1. Executive Summary", 14, 55);

        autoTable(doc, {
            startY: 60,
            head: [['Category', 'Success Indicator', 'Metric Value']],
            body: [
                ['Reminders', 'Trigger Accuracy', `${data.reminderPerformance.triggeredOnTime}%`],
                ['Notifications', 'Delivery Rate', `${data.notificationDelivery.readRate}%`],
                ['Medications', 'Adherence Index', `${data.medicationAdherence.missedRemindersCount} Missed`],
                ['Appointments', 'Compliance Status', `${data.appointmentCompliance.withReminders} with Reminders`],
                ['System Health', 'Reliability Index', `${data.systemHealth.retrySuccessRate}% Success Rate`]
            ],
            theme: 'striped',
            headStyles: { fillColor: [52, 152, 219] }
        });

        // 3. Reminder Performance
        const finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(16);
        doc.text("2. Reminder Performance", 14, finalY);

        autoTable(doc, {
            startY: finalY + 5,
            head: [['Metric', 'Value']],
            body: [
                ['Total Reminders Created', data.reminderPerformance.totalCreated],
                ['Missed Triggers', data.reminderPerformance.missedTriggers],
                ['Auto-Generated (Med)', data.reminderPerformance.autoGenerated],
                ['Manually Created', data.reminderPerformance.manuallyCreated]
            ],
            theme: 'plain'
        });

        // 4. Notification Delivery
        const finalY2 = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(16);
        doc.text("3. Notification Delivery", 14, finalY2);

        autoTable(doc, {
            startY: finalY2 + 5,
            head: [['Metric', 'Value']],
            body: [
                ['Total Sent', data.notificationDelivery.totalSent],
                ['Successful Delivery', data.notificationDelivery.deliveredCount],
                ['Failed Count', data.notificationDelivery.failedCount],
                ['Average Retries', data.notificationDelivery.averageRetries.toFixed(2)],
                ['Acknowledgement Rate', `${data.notificationDelivery.acknowledgementRate}%`]
            ],
            theme: 'plain'
        });

        // 5. Footer
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(
                "This report is for audit and accountability purposes. CareLink System Internal Document.",
                14,
                doc.internal.pageSize.getHeight() - 10
            );
            doc.text(
                `Page ${i} of ${pageCount}`,
                doc.internal.pageSize.getWidth() - 30,
                doc.internal.pageSize.getHeight() - 10
            );
        }

        doc.save(`CareLink_Audit_${Date.now()}.pdf`);
    },

    downloadBlob: (blob: Blob, filename: string) => {
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', filename);
        document.body.appendChild(link);
        link.click();
        link.remove();
    }
};
